# Generated by Django 4.2.8 on 2024-10-19 15:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_alter_photo_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=ckeditor.fields.RichTextField(default='abc'),
            preserve_default=False,
        ),
    ]
