# Generated by Django 4.2.8 on 2024-10-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='summary',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
