# Generated by Django 4.2.8 on 2024-10-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_category_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
