# Generated by Django 4.2.8 on 2024-11-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_alter_project_lng'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id']},
        ),
    ]
