# Generated by Django 4.2.8 on 2024-11-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_alter_post_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/articles/<django.db.models.fields.SlugField>', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/posts/<django.db.models.fields.SlugField>', verbose_name='Фото'),
        ),
    ]
