# Generated by Django 4.2.8 on 2024-11-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0024_alter_article_photo_alter_post_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
