# Generated by Django 4.2.8 on 2024-11-23 11:20

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0025_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=job.models.upload_to, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=job.models.upload_to, verbose_name='Фото'),
        ),
    ]
