# Generated by Django 4.2.8 on 2024-12-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0027_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tg_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
