# Generated by Django 4.2.8 on 2024-12-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0028_contact_tg_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='contact',
            name='tg_username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
