# Generated by Django 4.2.8 on 2024-12-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0029_alter_contact_options_alter_contact_tg_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='verification_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
