# Generated by Django 4.2.8 on 2025-01-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0030_alter_contact_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='verification_code',
        ),
    ]
