# Generated by Django 4.2.8 on 2025-01-04 09:38

import django.core.validators
from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0031_remove_contact_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator('Invalid email address.')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=job.models.photo_upload),
        ),
    ]
