# Generated by Django 4.2.8 on 2025-02-06 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0033_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.article')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='articles',
            field=models.ManyToManyField(related_name='posts', through='job.PostArticle', to='job.article'),
        ),
    ]
