# Generated by Django 4.2.8 on 2025-02-08 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0034_postarticle_post_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='summary',
        ),
    ]
