# Generated by Django 4.2.8 on 2025-02-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0035_remove_post_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='summary',
        ),
    ]
