# Generated by Django 4.2.8 on 2025-02-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0036_remove_category_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
