# Generated by Django 4.2.8 on 2025-02-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0037_post_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='category',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
