# Generated by Django 4.2.8 on 2025-02-17 07:31

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0038_alter_post_options_category_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to=job.models.upload_to),
        ),
    ]
