# Generated by Django 4.2.11 on 2025-03-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0039_alter_article_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title']},
        ),
    ]
