# Generated by Django 4.2.8 on 2025-04-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0041_userprofile_userquestion_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='telegram_photos/'),
        ),
    ]
