# Generated by Django 4.2.8 on 2025-04-02 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0042_remove_userprofile_photo_url_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
