# Generated by Django 4.2.11 on 2025-11-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0043_userprofile_auth_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("surname", models.CharField(max_length=150)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("education", models.CharField(blank=True, max_length=255)),
                (
                    "professional_education",
                    models.CharField(blank=True, max_length=255),
                ),
                ("additional_education", models.TextField(blank=True)),
                ("place_of_residence", models.CharField(blank=True, max_length=255)),
                ("ready_for_business_trip", models.BooleanField(default=False)),
                ("telephone_number", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
