# Generated by Django 4.2.11 on 2025-11-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0044_applicantprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicantprofile",
            name="position",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
